sudo: required 
services:
  -docker

before_install:
  - docker build -t akashchauhann/docker-react-basic -f Dockerfile.dev .

script:
  - docker run akashchauhann/docker-react-basic npm run test -- --coverage